arb-dir: lib/l10n
output-dir: lib/l10n
untranslated-messages-file: lib/l10n/missing_localizations.json
template-arb-file: strings_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: 'en'
synthetic-package: false
use-deferred-loading: false
nullable-getter: false
# header-file: app_localizations_header.dart
