name: flutter_web_portfolio
description: Portfolio Site.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  equatable: ^2.0.5
  auto_route: ^7.8.4
  responsive_framework: ^1.1.1
  syncfusion_flutter_core: ^23.1.44
  syncfusion_flutter_datagrid: ^23.1.44

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.2
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
